services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=algoritma
      - MYSQL_DATABASE=algoritma
    networks:
      - algoritma

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=algoritma
      - POSTGRES_PASSWORD=algoritma
      - POSTGRES_DATABASE=algoritma
    networks:
      - algoritma

networks:
  algoritma:
    external: true
